### ISSUE TITLE
2. Blockly Generation

### ISSUE THREAD

**Issue by KimHunJin** [SoftwareMaestro-Chaining/Chaining-Web-IDE#3]
## 블록 코딩 to 텍스트 코딩 제네레이션 작업

- [x] 1. multiple contract block
- [x] 2. payable, view block
- [x] 3. option ; inheritance
- [x] 4. msg block

**Comment by KimHunJin** [comment]
![image](https://user-images.githubusercontent.com/7833598/46275904-692c9e00-c599-11e8-9941-d2df18f44074.png)

[add]
1. multiple contract block complete

[bug]
1. exception

**Comment by SoojiNoh** [comment]
<img width="1298" alt="2018-10-01 5 42 52" src="https://user-images.githubusercontent.com/18151231/46278591-8bc2b500-c5a1-11e8-9051-e898fd03a253.png">
[add]
added msg block which includes gas, sender, data

**Comment by SoojiNoh** [comment]
- [ ] 5. Struct - 'Array' Block

- [ ] 6. 'Mapping' Block

- [ ] 7. 'Struct' initializer and getter

**Comment by KimHunJin** [comment]
![image](https://user-images.githubusercontent.com/7833598/46334414-e5d58000-c65e-11e8-9378-c7f0f60ca1f9.png)

[add]
2-2. payable and view block

**Comment by KimHunJin** [comment]
![image](https://user-images.githubusercontent.com/7833598/46342260-47a0e480-c675-11e8-88a0-c0d37166c844.png)

[add]
2-3. inheritance

[to do]
inheritance change dynamic drop down block
